#ifndef _SETTINGS_H
#define _SETTINGS_H

#define FORMULAS_DIR "Tex/"

enum CodeError
{
    NO_ERR,

    FILE_NOT_OPENED_ERR,
    FILLING_FILE_STAT_ERR,
    WRONG_INPUT_BUFSIZE_ERR,

    FILE_READING_SYNTAX_ERR,
    MET_EOF_DURING_READING_ERR,

    ZERO_DIVISION_ERR,
    UNKNOWN_NODE_VALUE_TYPE_ERR,
};

#endif
